name: doctor_care
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  #webview_flutter: ^3.0.4
  dio: ^4.0.6
  #shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.0
  intl: ^0.17.0
  flutter_iconly: ^1.0.2
  easy_localization: ^3.0.1
  flutter_native_splash: ^2.2.3+1
  dropdown_button2: ^1.6.3
  file_picker: ^4.6.0
  cached_network_image: ^3.2.1
  #http: ^0.13.4
  image_picker: ^0.8.5+3
  #syncfusion_flutter_pdfviewer: ^20.1.58-beta
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  #url_launcher: ^6.1.4
  #pdf: ^3.8.1
  #open_file: ^3.1.0
  #animations: ^2.0.3
  #flutter_local_notifications: ^9.4.0


  cupertino_icons: ^1.0.5
  sliding_clipped_nav_bar: ^3.1.0+2
  awesome_dialog: ^2.2.1
  carousel_slider: ^4.1.1
  hovering: ^1.0.4
  smooth_page_indicator: ^1.0.0+2
  mouse_parallax: ^1.1.0
  animated_custom_dropdown: ^1.2.2
  scrollable_positioned_list: ^0.3.2
  geolocator: ^9.0.1
  #geocode: ^1.0.2
  #geocoding: ^2.0.4
  #persistent_bottom_nav_bar: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  hive_generator: ^1.1.3

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/image/logo/splash_logo.png
  color_dark: "#FFFFFF"
  image_dark: assets/image/logo/splash_logo.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo/launcher_logo.png"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/translation/
    - assets/image/logo/
    - assets/image/main_images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf

